apiVersion: v2
name: frdemo
description: frdemo Helm chart for Openshift
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: postgresql
    version: "12.2.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled