name: frdemo-backend
image:
  name: jimmarh/backend:latest
  pullPolicy: Always
autoscaling:
  enabled: false
replicaCount: 1
deploy:
  kafkaserver: kafka-service
  enabled: true
  replicas: 1
  tls: {}
  route:
    enabled: true
    tls:
      enabled: true
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
  livenessProbe:
    httpGet:
      path: /health/live
      port: admin
  readinessProbe:
    httpGet:
      path: /health/ready
      port: admin
  startupProbe:
    httpGet:
      path: /health/live
      port: admin
service:
  port: 80
postgresql:
  enabled: true
  database:
    name: frdemo
    username: postgres
    password: postgres
  service:
    name: postgresql
    type: ClusterIP
kafaka:
   enabled: true
   service:
     name: kafka-service
   type: ClusterIP
zookeeper:
   enabled: true
   service:
     name: zookeeper-service




