name: frdemo-backend
image:
  name: jimmarh/backend:mapbox
  pullPolicy: Always
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 100
deploy:
  kafkaserver: kafka-service
  enabled: true
  resources:
    requests:
      memory: "500Mi"
      cpu: "100m"
  tls: {}
  route:
    enabled: true
    tls:
      enabled: true
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
  livenessProbe:
    httpGet:
      path: /health/live
      port: admin
  readinessProbe:
    httpGet:
      path: /health/ready
      port: admin
  startupProbe:
    httpGet:
      path: /health/live
      port: admin
service:
  port: 80
postgresql:
  enabled: true
  database:
    name: frdemo
    username: postgres
    password: postgres
  service:
    name: postgresql
    type: ClusterIP
kafaka:
   enabled: true
   service:
     name: kafka-service
   type: ClusterIP
zookeeper:
   enabled: true
   service:
     name: zookeeper-service
mapbox:
   service:
     name: http://mapbox-service




