apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: swagger-route
spec:
  to:
    kind: Service
    name: swagger-service
    weight: 100
---
apiVersion: v1
kind: Service
metadata:
  name: swagger-service
spec:
  selector:
    app: swagger
  ports:
    - name: swagger-port
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: v1
kind: Pod
metadata:
  name: swagger
  labels:
    app: swagger
spec:
  containers:
    - name: swagger
      image: swaggerapi/swagger-ui:latest
      env:
        - name: SWAGGER_JSON_URL
          value: https://frdemo-rhn-engineering-ema-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com/openapi?format=JSON
