# Default values for postgresql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  name: confluentinc/cp-kafka:latest
  pullPolicy: Always
service:
  name: kafka-service
  type: ClusterIP
  port: 9092
zookeeper:
  enabled: true
  service: zookeeper-service
