# Default values for postgresql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  name: confluentinc/cp-zookeeper:latest
  pullPolicy: Always
service:
  name: zookeeper-service
  type: ClusterIP
  port: 2181
