apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 9092
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  sessionAffinity: None
