apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgresql.pvcName" . }}
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi