apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 5432
  selector:
    {{- include "postgresql.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  sessionAffinity: None

